### ISSUE TITLE
Its broken when you use zoom functionality of canvas

### ISSUE THREAD

**Issue by bcalik** [taqimustafa/fabricjs-polygon#1]
Hello drawing is not working when zoom factor is changed.
You can try on demo page:
http://taqimustafa.com/demo/polygon/

Type `canvas.setZoom(0.5)` to the console. Then try to draw.

**Comment by taqimustafa** [comment]
Please pull the files again. Issue fixed

https://github.com/taqimustafa/fabricjs-polygon/commit/50f8d202d65546a860b49dc733a963512db96c31
