### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MaxLeiter** [taqimustafa/fabricjs-polygon#2]
I would like to use this in a project, but no license is provided

**Comment by taqimustafa** [comment]
@MaxLeiter i think fabricjs has a License doc. https://github.com/kangax/fabric.js/blob/master/LICENSE

I am just using that library. Didn't had time to fix some issues, but please feel free to use it.

**Comment by MaxLeiter** [comment]
But the license doesn't pass to your work

**Comment by taqimustafa** [comment]
It's open source, you can use it. Will add an open source license soon.
