### ISSUE TITLE
Need Help to draw multiple polygon

### ISSUE THREAD

**Issue by abureviewer1** [taqimustafa/fabricjs-polygon#3]
Hi, Your script is super I need to draw multiple polygon can you help me how to do it?

**Comment by abureviewer1** [comment]
Sorry I didn't click "Create Polygon" another time your code is Excellent

**Comment by taqimustafa** [comment]
@abureviewer1 it has some issue now maybe because of the fabricjs verison, i will try to fix that when i have some spare time. Thanks for using it 👍

**Comment by taqimustafa** [comment]
@abureviewer1 it has some issue now maybe because of the fabricjs verison, i will try to fix that when i have some spare time. Thanks for using it 👍
