### ISSUE TITLE
activeShape problem with fabric 1.7.11

### ISSUE THREAD

**Issue by daer-ru** [taqimustafa/fabricjs-polygon#4]
Hi. Thanks for your script.
Maybe you can help me with one problem?

I use fabric 1.7.11 and activeShape draw only in area wich 90 degrees between first and last point.

Here is your code with fabric 1.7.11
https://codepen.io/daer_ru/pen/pdOMyX

**Comment by daer-ru** [comment]
I found answer on [stackoverflow](https://stackoverflow.com/questions/47570312/fabric-js-draw-polygon-with-active-shape) :)

**Comment by taqimustafa** [comment]
@daer-ru i really wish i had time to update the code, because its a bit buggy. But i hope that some how the logic helped you in some way.
